# Form implementation generated from reading ui file 'inter.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_receiver = QtWidgets.QLabel(parent=MainWindow)
        self.lbl_receiver.setObjectName("lbl_receiver")
        self.verticalLayout.addWidget(self.lbl_receiver)
        self.cmb_receiver = QtWidgets.QComboBox(parent=MainWindow)
        self.cmb_receiver.setObjectName("cmb_receiver")
        self.verticalLayout.addWidget(self.cmb_receiver)
        self.lbl_country = QtWidgets.QLabel(parent=MainWindow)
        self.lbl_country.setObjectName("lbl_country")
        self.verticalLayout.addWidget(self.lbl_country)
        self.cmb_country = QtWidgets.QComboBox(parent=MainWindow)
        self.cmb_country.setObjectName("cmb_country")
        self.verticalLayout.addWidget(self.cmb_country)
        self.lbl_commission = QtWidgets.QLabel(parent=MainWindow)
        self.lbl_commission.setObjectName("lbl_commission")
        self.verticalLayout.addWidget(self.lbl_commission)
        self.lbl_amount = QtWidgets.QLabel(parent=MainWindow)
        self.lbl_amount.setObjectName("lbl_amount")
        self.verticalLayout.addWidget(self.lbl_amount)
        self.txt_amount = QtWidgets.QLineEdit(parent=MainWindow)
        self.txt_amount.setObjectName("txt_amount")
        self.verticalLayout.addWidget(self.txt_amount)
        self.btn_transfer = QtWidgets.QPushButton(parent=MainWindow)
        self.btn_transfer.setObjectName("btn_transfer")
        self.verticalLayout.addWidget(self.btn_transfer)
        self.lbl_history = QtWidgets.QLabel(parent=MainWindow)
        self.lbl_history.setObjectName("lbl_history")
        self.verticalLayout.addWidget(self.lbl_history)
        self.txt_history = QtWidgets.QTextEdit(parent=MainWindow)
        self.txt_history.setReadOnly(True)
        self.txt_history.setObjectName("txt_history")
        self.verticalLayout.addWidget(self.txt_history)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Денежные переводы"))
        self.lbl_receiver.setText(_translate("MainWindow", "Выберите получателя:"))
        self.lbl_country.setText(_translate("MainWindow", "Выберите страну перевода:"))
        self.lbl_commission.setText(_translate("MainWindow", "Комиссия: Не выбрана"))
        self.lbl_amount.setText(_translate("MainWindow", "Сумма перевода:"))
        self.btn_transfer.setText(_translate("MainWindow", "Совершить перевод"))
        self.lbl_history.setText(_translate("MainWindow", "История переводов:"))
